### ISSUE TITLE
/api/v1/bookmarks panics with index out of range error

### ISSUE THREAD

**Issue by erka** [davecheney/pub#12]
Hey! 👋

If user has no bookmarks `pub` panics with log

```
http: panic serving 127.0.0.1:50638: runtime error: index out of range [-1]
goroutine 499 [running]:
net/http.(*conn).serve.func1()
go1.20rc2/src/net/http/server.go:1854 +0xbf
panic({0x15d5e80, 0xc0003a2420})
go1.20rc2/src/runtime/panic.go:890 +0x263
github.com/davecheney/pub/mastodon.BookmarksIndex(0xc0003be2f0, {0x16e3460, 0xc00037a0e0}, 0xc00030ad00)
pub/mastodon/bookmarks.go:29 +0x5c5
```

**Comment by davecheney** [comment]
Thanks for the bug report, i'll get it fixed today.
